name: Test and Lint

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      skip_approval_check:
        required: false
        type: boolean
        default: false

jobs:
  check-approval:
    name: Check if PR has contributor approval
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    # Skip this check if explicitly requested or if this is a release workflow
    if: inputs.skip_approval_check != true && github.event_name == 'pull_request'
    outputs:
      approved: ${{ steps.check-approval.outputs.approved }}
    steps:
      - name: Check if PR has been approved by a contributor
        id: check-approval
        uses: actions/github-script@v7
        with:
          script: |
            const APPROVED_ASSOCIATION = ['COLLABORATOR',  'CONTRIBUTOR', 'MEMBER', 'OWNER']
            const PR_AUTHOR_ASSOCIATION = context.payload.pull_request.author_association;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const isApprovedContributor = APPROVED_ASSOCIATION.includes(PR_AUTHOR_ASSOCIATION);
            
            // Check if any contributor has approved                                                              
             const isApproved = reviews.some(review =>                                                             
               review.state === 'APPROVED' && APPROVED_ASSOCIATION.includes(review.author_association)                      
             ) || isApprovedContributor;                                                                                                    
            
            core.setOutput('approved', isApproved);
            
            if (!isApproved) {
              core.notice('This PR does not have approval from a Contributor. Workflow will not run test jobs.');
              return false;
            }
            
            return true;

  unit-test:
    name: Unit Tests - Python ${{ matrix.python-version }} - ${{ matrix.os-name }}
    needs: [check-approval]
    permissions:
      contents: read
    # Only run if PR is approved, or if approval check is skipped, or if this is a direct push to main
    if: always() && (needs.check-approval.result == 'skipped' || needs.check-approval.outputs.approved == 'true' || inputs.skip_approval_check == true)
    strategy:
      matrix:
       include:
        # Linux
        - os: ubuntu-latest
          os-name: 'linux'
          python-version: "3.10"
        - os: ubuntu-latest
          os-name: 'linux'
          python-version: "3.11"
        - os: ubuntu-latest
          os-name: 'linux'
          python-version: "3.12"
        - os: ubuntu-latest
          os-name: 'linux'
          python-version: "3.13"
        # Windows
        - os: windows-latest
          os-name: 'windows'
          python-version: "3.10"
        - os: windows-latest
          os-name: 'windows'
          python-version: "3.11"
        - os: windows-latest
          os-name: 'windows'
          python-version: "3.12"
        - os: windows-latest
          os-name: 'windows'
          python-version: "3.13"
        # MacOS - latest only; not enough runners for macOS
        - os: macos-latest
          os-name: 'macOS'
          python-version: "3.13"
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      LOG_LEVEL: DEBUG
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}  # Explicitly define which commit to check out
          persist-credentials: false  # Don't persist credentials for subsequent actions
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --no-cache-dir hatch
      - name: Run Unit tests
        id: tests
        run: hatch test tests --cover
        continue-on-error: false

  test-install:
    name: Dependency Check - Python ${{ matrix.python-version }}
    needs: [check-approval]
    runs-on: ubuntu-latest
    # Only run if PR is approved, or if approval check is skipped, or if this is a direct push to main
    if: always() && (needs.check-approval.result == 'skipped' || needs.check-approval.outputs.approved == 'true' || inputs.skip_approval_check == true)
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      # If we ever need to be more frugal, we can run this 1x1   
      # max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for different targets
        run: |
          pip install -e . --python-version ${{ matrix.python-version }} --target ./manylinux2014_x86_64  --platform manylinux2014_x86_64 --only-binary=:all:
          pip install -e . --python-version ${{ matrix.python-version }} --target ./manylinux2014_aarch64 --platform manylinux2014_aarch64 --only-binary=:all:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [check-approval]
    permissions:
      contents: read
    # Only run if PR is approved, or if approval check is skipped, or if this is a direct push to main
    if: always() && (needs.check-approval.result == 'skipped' || needs.check-approval.outputs.approved == 'true' || inputs.skip_approval_check == true)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir hatch

      - name: Run lint
        id: lint
        run: hatch run test-lint
        continue-on-error: false
